name: Build and Deploy Angular App

on:
  push:
    branches:
      - master  # Replace with your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust the Node version based on your Angular setup

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

      - name: Copy dist files to server
        env:
          SSH_HOST: ${{ vars.PROD_HOST }}
          SSH_USER: ${{ vars.PROD_HOST_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: '22'
        run: |
          # Save the SSH key to a file
          echo "$SSH_KEY" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          
          # Use SCP to transfer files to the server (REPLACE THIS PART)
          scp -P $SSH_PORT -i /tmp/deploy_key -r dist/bispado-online-frontend $SSH_USER@$SSH_HOST:/var/www/BispadoOnline-Frontend

          # Optionally, clean up the key
          rm /tmp/deploy_key